### ISSUE TITLE
Comment after package name.

### ISSUE THREAD

**Issue by pjanzen** [layeh/gopher-json#1]
In de .go files in gopher-json there is a comment after package <name>.

This causes the following error:
workflow/queue.go:13:2: code in directory /Volumes/external_disk/Ziggo/Git/Go/src/github.com/layeh/gopher-json expects import "layeh.com/gopher-json"

I changed this:
package json // import "layeh.com/gopher-json"

to this:
package json

for all the go files in layeh.com/gopher-json and now my code compiles fine.
The go version I use is:
go version go1.7.4 darwin/amd64

If you require any more information please let me know.

Paul.

**Comment by ghost** [comment]
A couple of weeks ago, I updated the import path of the project. You should do the following:

1. Run `go get -u layeh.com/gopher-json`
2. Update all of your import statements from `github.com/layeh/gopher-json` to `layeh.com/gopher-json`
