### ISSUE TITLE
encode LTable to JSON Array

### ISSUE THREAD

**Issue by deefdragon** [layeh/gopher-json#5]
Would it be possible, and within the scope of this library, to add a function that imported numeric keys in a table to an array instead of an object with the label of the number?

**Comment by ghost** [comment]
I don't think I fully understand what you're requesting. Could you provide some code with expected output and actual output? Thanks.

**Comment by deefdragon** [comment]
In lua, arrays are basically just maps with numeric keys. the code 
```
a = {}    -- new array
for i=1, 1000 do
    a[i] = i
end
```
creates a table with matching indexes and values. currently, this library converts this to JSON by creating an object who's name is the string representation of the integer value

```
{
  "1":1,
  "2":2,
  "3":3 
   ...
}
```
I am wondering if it would be possible to have a special case included in this library where integer indexes are put into arrays.
```
[
  1,
  2,
  3
  ...
]
```

Because of the nature of lua tables, it would either have to be limited to special cases where the indexes are ONLY integers

```
[
    1,
    2,
    3
   ...
]
```

or a reserved name would have to be chosen(or be an argument) to be able to work with other keys/indexes.
```
{
  "Name": "integers",
  "array_values": [
    1,
    2,
    3
   ...
  ]
}
```

 If it was reserved, I suspect that it would be handled the same way that a[1] and a["1"] are different in the table, but have the same value in the JSON. (I don't know how the library currently handles this, but I suspect that it throws an error. )

**Comment by ghost** [comment]
The library already does do this.  See the test I just pushed: d0a7d8b4c69aea3341d0131a64b59a6df9759be2

**Comment by deefdragon** [comment]
Ok, I ran a test myself. I figured out that the issue was that I started at 0, which then results in 
`{"0":0,"1":1,"2":2,"3":3,"4":4,"5":5}` 
Understandable albeit a bit confusing considering that goalng is 0 indexed vs lua's 1 indexing. Something for the documentation.
