### ISSUE TITLE
Stable decode/encode with empty maps and arrays

### ISSUE THREAD

**Issue by j-vizcaino** [layeh/gopher-json#8]
The library does not seem to support propagating original type when decoding/encoding empty maps and arrays.

As a result:

* decoding an empty map leads to an empty Lua table (expected)
* decoding an empty array leads to an empty Lua table (expected as well since Lua makes no difference between maps and arrays)
* encoding an empty table leads to "null": this is unexpected and breaks stability of encode/decode process.

In order to illustrate the issue, I have created a test-case (see associated PR #7)

**Comment by ghost** [comment]
I'm not sure what can be done here. Without any entries in the table, we can't know whether the item is intended to be an object or an array.

**Comment by j-vizcaino** [comment]
I agree the use-case for empty arrays from Lua is tricky since the language implements this using a table.
Anyway, there should be a simple way to fix the empty table getting JSON encoded as `null` (instead of the expected `{}`).
Now in order to provide stability between encode and decode, maybe user-types could be used (though I don't know if the library has complete support for that).

I'll update #7 tomorrow to fix the "empty table gets marshalled as `null`" issue and leave the array case for now since there's no easy way out of this.

**Comment by ghost** [comment]
I've ensured that the encoding rules mimic that of [json.lua](https://github.com/rxi/json.lua):

```
//  Lua      | JSON
//  ---------+-----
//  nil      | null
//  number   | number
//  string   | string
//  table    | object: when table is non-empty and has only string keys
//           | array:  when table is empty, or has only sequential numeric keys
//           |         starting from 1
```
